name:                 fastpass
version:              0.1.0.0
visibility:           public
id:                   fastpass-0.1.0.0-76OKmYOHMrHH8OHWXHFIAN
key:                  fastpass-0.1.0.0-76OKmYOHMrHH8OHWXHFIAN
license:              BSD-3-Clause
copyright:            "2025 Jaroslav Mihajlenko"
maintainer:           malledeferlive@gmail.com
author:               ruzen42
homepage:             https://github.com/ruzen42/fastpass
synopsis:             simple passwords generation program
description:          simple passwords generation program
category:             System
abi:                  cfd51b0a24b7322857aef166bf142605
exposed:              True
exposed-modules:      RandomGenerator
import-dirs:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/lib/x86_64-linux-ghc-9.10.2-35d5/fastpass-0.1.0.0-76OKmYOHMrHH8OHWXHFIAN

library-dirs:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/lib/x86_64-linux-ghc-9.10.2-35d5/fastpass-0.1.0.0-76OKmYOHMrHH8OHWXHFIAN

library-dirs-static:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/lib/x86_64-linux-ghc-9.10.2-35d5/fastpass-0.1.0.0-76OKmYOHMrHH8OHWXHFIAN

dynamic-library-dirs:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/lib/x86_64-linux-ghc-9.10.2-35d5

data-dir:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/share/x86_64-linux-ghc-9.10.2-35d5/fastpass-0.1.0.0

hs-libraries:         HSfastpass-0.1.0.0-76OKmYOHMrHH8OHWXHFIAN
depends:
    base-4.20.1.0-c866 random-1.2.1.3-3nttR370PiJJVLpc2ETFkT

haddock-interfaces:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/doc/fastpass-0.1.0.0/fastpass.haddock

haddock-html:
    /home/ruzen42/src/fastpass/.stack-work/install/x86_64-linux/b0e18f6dca427632bfca93750fea1327ed16622e20180799c85f4f707de7939d/9.10.2/doc/fastpass-0.1.0.0
